@WepApi_HostAddress = http://localhost:5227

POST {{WepApi_HostAddress}}/item
Content-Type: application/json
Accept: application/json

{
  "name": "HP Fury G8",
  "description": "Workstation laptop",
  "tags": ["Laptop"],
  "quantity": 100
}
